"use client";

import { useQuery } from "@tanstack/react-query";
import { getReceiptSummary, getChallengeSummary, type SummaryResponse } from "@/lib/api";

interface GeminiSummaryCardProps {
  kind: "receipt" | "challenge";
  referenceId: string;
}

export function GeminiSummaryCard({ kind, referenceId }: GeminiSummaryCardProps) {
  const { data: summary, isLoading, error } = useQuery<SummaryResponse>({
    queryKey: ["gemini-summary", kind, referenceId],
    queryFn: () =>
      kind === "receipt"
        ? getReceiptSummary(referenceId)
        : getChallengeSummary(referenceId),
    retry: 1,
    staleTime: 5 * 60 * 1000,
    enabled: !!referenceId,
  });

  if (isLoading) {
    return (
      <div className="border border-rule rounded-lg p-5 animate-pulse">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-[11px] font-mono tracking-wider text-text-tertiary uppercase">
            Gemini Advisory
          </span>
          <span className="h-px flex-1 bg-rule" />
          <span className="text-[10px] font-mono text-text-quat">Loading...</span>
        </div>
        <div className="h-4 bg-surface-raised rounded w-3/4 mb-2" />
        <div className="h-3 bg-surface-raised rounded w-1/2" />
      </div>
    );
  }

  if (error || !summary) {
    return null;
  }

  return (
    <div className="border border-rule rounded-lg p-5">
      <div className="flex items-center gap-2 mb-4">
        <span className="text-[11px] font-mono tracking-wider text-accent uppercase font-medium">
          Gemini Advisory Summary
        </span>
        <span className="h-px flex-1 bg-rule" />
        <span className="text-[10px] font-mono text-text-quat">
          {summary.model} · advisory only
        </span>
      </div>

      <h3
        className="font-display font-semibold text-text-primary mb-3"
        style={{ fontSize: "var(--t-lg)" }}
      >
        {summary.headline}
      </h3>

      <ul className="space-y-1.5 mb-4">
        {summary.summaryBullets.map((bullet, i) => (
          <li key={i} className="flex items-start gap-2 text-[13px] text-text-secondary">
            <span className="text-accent mt-0.5 shrink-0">•</span>
            <span>{bullet}</span>
          </li>
        ))}
      </ul>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-[12px]">
        <div>
          <span className="eyebrow block mb-1">Risk Assessment</span>
          <p className="text-text-secondary">{summary.riskAssessment}</p>
        </div>
        <div>
          <span className="eyebrow block mb-1">Why Allowed / Blocked</span>
          <p className="text-text-secondary">{summary.whyItWasAllowedOrBlocked}</p>
        </div>
      </div>

      {summary.recommendedReviewerFocus.length > 0 && (
        <div className="mt-4 pt-3 border-t border-rule">
          <span className="eyebrow block mb-2">Reviewer Focus</span>
          <ul className="space-y-1">
            {summary.recommendedReviewerFocus.map((focus, i) => (
              <li key={i} className="text-[12px] text-text-tertiary flex items-start gap-2">
                <span className="text-warning mt-0.5 shrink-0">→</span>
                <span>{focus}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <p className="mt-4 text-[10px] text-text-quat font-mono">
        This summary is generated by Gemini for advisory purposes only. It does not affect
        deterministic on-chain outcomes. All guardrail decisions are made by the on-chain
        policy engine.
      </p>
    </div>
  );
}
