/**
 * ChallengeArbiter ABI — derived from `contracts/interfaces/IChallengeArbiter.sol`.
 *
 * Regenerated by Dev 3 to fix ABI drift found by
 * `services/infra/test/abi-parity.test.ts`:
 *   - ChallengeFiled previously declared 2 fields (`challengeType`, `bondAmount`)
 *     that don't exist in the on-chain interface — its topic hash was wrong
 *     and the dashboard would never have matched a real ChallengeFiled log.
 *   - ChallengeResolved previously used `upheld / slashAmount / payoutTo`
 *     — the real interface emits `uphold / payout` only.
 */

export const challengeArbiterAbi = [
  // --- User-facing ---
  {
    type: "function",
    name: "fileAmountViolation",
    inputs: [{ name: "receiptId", type: "bytes32" }],
    outputs: [{ name: "challengeId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveByReviewer",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "uphold", type: "bool" },
      { name: "slashAmount", type: "uint256" },
      { name: "reviewerSig", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // --- Views ---
  {
    type: "function",
    name: "CHALLENGE_BOND",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "reviewerSigner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "USDC",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },

  // --- Admin ---
  {
    type: "function",
    name: "setReviewerSigner",
    inputs: [{ name: "signer", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // --- Events ---
  {
    type: "event",
    name: "ChallengeFiled",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "receiptId", type: "bytes32", indexed: true },
      { name: "challenger", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChallengeResolved",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "uphold", type: "bool", indexed: false },
      { name: "payout", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ReviewerSignerUpdated",
    inputs: [
      { name: "previous", type: "address", indexed: true },
      { name: "current", type: "address", indexed: true },
    ],
    anonymous: false,
  },

  // --- Errors ---
  { type: "error", name: "ReceiptNotFound", inputs: [] },
  { type: "error", name: "ChallengeWindowClosed", inputs: [] },
  { type: "error", name: "NotOverspend", inputs: [] },
  { type: "error", name: "InvalidReviewerSignature", inputs: [] },
  { type: "error", name: "ChallengeAlreadyResolved", inputs: [] },
  { type: "error", name: "ZeroSigner", inputs: [] },
] as const;
