/**
 * GuardedExecutor ABI — derived from `contracts/interfaces/IGuardedExecutor.sol`
 * + `contracts/interfaces/IGuardTypes.sol` (Dev 1, frozen at hour 4).
 *
 * Regenerated by Dev 3 to fix three production-killing bugs found by
 * `services/infra/test/abi-parity.test.ts`:
 *   - `ActionReceipt.agentId` must be `indexed: true`
 *   - `ActionReceipt.timestamp` must be `uint64` (not uint256)
 *   - `ReceiptStored` and `TraceURIStored` were missing entirely
 *
 * Keep this file in sync with the Solidity interface — the on-chain
 * topic hashes are derived from the (name, types, indexed) tuple, so any
 * drift here = the dashboard silently misses events.
 */

export const guardedExecutorAbi = [
  // --- Owner-scoped ---
  {
    type: "function",
    name: "setAgentDelegate",
    inputs: [
      { name: "agentId", type: "bytes32" },
      { name: "delegate", type: "address" },
      { name: "approved", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // --- Delegate-scoped ---
  {
    type: "function",
    name: "preflightCheck",
    inputs: [
      {
        name: "req",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "agentId", type: "bytes32" },
          { name: "target", type: "address" },
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "data", type: "bytes" },
          { name: "traceURI", type: "string" },
          {
            name: "traceAck",
            type: "tuple",
            components: [
              { name: "contextDigest", type: "bytes32" },
              { name: "uriHash", type: "bytes32" },
              { name: "expiresAt", type: "uint64" },
              { name: "signature", type: "bytes" },
            ],
          },
        ],
      },
    ],
    outputs: [
      { name: "decision", type: "uint8" },
      { name: "reasonCode", type: "bytes32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "executeWithGuard",
    inputs: [
      {
        name: "req",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "agentId", type: "bytes32" },
          { name: "target", type: "address" },
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "data", type: "bytes" },
          { name: "traceURI", type: "string" },
          {
            name: "traceAck",
            type: "tuple",
            components: [
              { name: "contextDigest", type: "bytes32" },
              { name: "uriHash", type: "bytes32" },
              { name: "expiresAt", type: "uint64" },
              { name: "signature", type: "bytes" },
            ],
          },
        ],
      },
    ],
    outputs: [{ name: "receiptId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },

  // --- Views ---
  {
    type: "function",
    name: "getReceipt",
    inputs: [{ name: "receiptId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "agentId", type: "bytes32" },
          { name: "intentHash", type: "bytes32" },
          { name: "target", type: "address" },
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "callDataHash", type: "bytes32" },
          { name: "contextDigest", type: "bytes32" },
          { name: "nonce", type: "uint256" },
          { name: "timestamp", type: "uint64" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isDelegateApproved",
    inputs: [
      { name: "owner", type: "address" },
      { name: "agentId", type: "bytes32" },
      { name: "delegate", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "spentToday",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "execNonce",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DOMAIN_SEPARATOR",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TRACE_ACK_TYPE",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "TRACE_ACK_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "traceAckSigner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "USDC",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },

  // --- Admin ---
  {
    type: "function",
    name: "setTraceAckSigner",
    inputs: [{ name: "signer", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // --- Events ---
  {
    type: "event",
    name: "AgentDelegateSet",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "agentId", type: "bytes32", indexed: true },
      { name: "delegate", type: "address", indexed: true },
      { name: "approved", type: "bool", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ActionReceipt",
    inputs: [
      { name: "receiptId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "agentId", type: "bytes32", indexed: true },
      { name: "intentHash", type: "bytes32", indexed: false },
      { name: "target", type: "address", indexed: false },
      { name: "token", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "callDataHash", type: "bytes32", indexed: false },
      { name: "contextDigest", type: "bytes32", indexed: false },
      { name: "nonce", type: "uint256", indexed: false },
      { name: "timestamp", type: "uint64", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ReceiptStored",
    inputs: [
      { name: "receiptId", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "intentHash", type: "bytes32", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TraceURIStored",
    inputs: [
      { name: "receiptId", type: "bytes32", indexed: true },
      { name: "traceURI", type: "string", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TraceAckSignerUpdated",
    inputs: [
      { name: "previous", type: "address", indexed: true },
      { name: "current", type: "address", indexed: true },
    ],
    anonymous: false,
  },

  // --- Errors ---
  { type: "error", name: "GuardRejected", inputs: [{ name: "reasonCode", type: "bytes32" }] },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "NotApprovedDelegate", inputs: [] },
  { type: "error", name: "ZeroSigner", inputs: [] },
] as const;
