/**
 * IntentRegistry ABI — derived from `contracts/interfaces/IIntentRegistry.sol`
 * + `contracts/interfaces/IGuardTypes.sol`.
 *
 * Regenerated by Dev 3 to add the views + errors the dashboard needs to:
 *   - resolve historical IntentConfigs when rendering challenges
 *     (`getIntent`)
 *   - validate forms before submit (`MAX_COUNTERPARTIES`, `USDC`)
 *   - render human-readable revert reasons (custom errors)
 */

export const intentRegistryAbi = [
  // --- Mutating ---
  {
    type: "function",
    name: "commitIntent",
    inputs: [
      { name: "intentHash", type: "bytes32" },
      {
        name: "cfg",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "token", type: "address" },
          { name: "maxSpendPerTx", type: "uint256" },
          { name: "maxSpendPerDay", type: "uint256" },
          { name: "allowedCounterparties", type: "address[]" },
          { name: "expiry", type: "uint64" },
          { name: "nonce", type: "uint256" },
        ],
      },
      { name: "manifestURI", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeIntent",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // --- Views ---
  {
    type: "function",
    name: "getActiveIntentHash",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getIntent",
    inputs: [{ name: "intentHash", type: "bytes32" }],
    outputs: [
      {
        name: "cfg",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "token", type: "address" },
          { name: "maxSpendPerTx", type: "uint256" },
          { name: "maxSpendPerDay", type: "uint256" },
          { name: "allowedCounterparties", type: "address[]" },
          { name: "expiry", type: "uint64" },
          { name: "nonce", type: "uint256" },
        ],
      },
      { name: "manifestURI", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_COUNTERPARTIES",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "USDC",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },

  // --- Events ---
  {
    type: "event",
    name: "IntentCommitted",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "intentHash", type: "bytes32", indexed: true },
      { name: "manifestURI", type: "string", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "IntentRevoked",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "intentHash", type: "bytes32", indexed: true },
    ],
    anonymous: false,
  },

  // --- Errors ---
  { type: "error", name: "IntentHashMismatch", inputs: [] },
  { type: "error", name: "CounterpartyListTooLong", inputs: [] },
  { type: "error", name: "IntentAlreadyExpired", inputs: [] },
  { type: "error", name: "NotIntentOwner", inputs: [] },
  { type: "error", name: "NonceNotStrictlyIncreasing", inputs: [] },
  { type: "error", name: "NotConfigOwner", inputs: [] },
  { type: "error", name: "TokenNotUsdc", inputs: [] },
] as const;
